spotify/klio

.github/workflows/audio.yml, .github/workflows/cli.yml, .github/workflows/devtools.yml, .github/workflows/exec.yml, .github/workflows/lib.yml, README.rst, audio/README.rst, cli/README.rst, core/README.rst, devtools/README.rst, docs/src/conf.py, examples/audio_spectrograms/README.rst, examples/audio_spectrograms/job-requirements.in, examples/audio_spectrograms/job-requirements.txt, examples/snippets/README.rst, examples/snippets/custom_ext_checks.py, exec/README.rst, lib/README.rst
* Update external RTDs links to new RTDs instance
* Add klio packages for the audio-spectrogram example
* Update CI workflows to include the "verify dev setup" step now that we have public PyPI packages.
=> [docs,ex,ci] Update links related to public PyPI and RTDs

lib/src/klio/__init__.py
Clarifies that Klio is conventions for Apache Beam broadly.
=> [lib] Updates Klio-lib library description

docs/src/.current_status.rst, docs/src/quickstart/index.rst, docs/src/quickstart/installation.rst, docs/src/reference/audio/index.rst, docs/src/reference/cli/index.rst, docs/src/reference/core/index.rst, docs/src/reference/devtools/index.rst, docs/src/reference/executor/index.rst, docs/src/reference/index.rst, docs/src/reference/lib/index.rst, docs/src/userguide/index.rst
=> [docs] Add current status caution admonition

docs/src/_static/css/custom.css, docs/src/_static/images/book-open.svg, docs/src/_static/images/code.svg, docs/src/_static/images/play.svg, docs/src/_static/images/terminal.svg, docs/src/_templates/layout.html
All of these have been requested by our design folks (commit msgs should be descriptive enough)
=> [docs] Small CSS updates

CONTRIBUTING.rst, README.rst, audio/README.rst, cli/README.rst, cli/src/klio_cli/commands/job/utils/templates/README.md.tpl, cli/src/klio_cli/commands/job/utils/templates/transforms-batch.py.tpl, cli/src/klio_cli/commands/job/utils/templates/transforms.py.tpl, cli/tests/commands/job/utils/fixtures/expected/README.md, cli/tests/commands/job/utils/fixtures/expected/transforms-batch.py, cli/tests/commands/job/utils/fixtures/expected/transforms.py, core/README.rst, devtools/README.rst, examples/audio_spectrograms/README.rst, examples/catvdog/README.rst, examples/snippets/README.rst, examples/snippets/custom_ext_checks.py, exec/README.rst, lib/README.rst, microsite/index.html
=> Site now live at klio.io and docs now live at docs.klio.io

docs/src/reference/lib/changelog.rst, lib/setup.cfg, lib/src/klio/__init__.py
=> [lib] Bump version: 0.2.0 → 0.2.0.post1

CONTRIBUTING.rst, RELEASING.rst, docs/src/conf.py
Figured these might be helpful.
=> [docs] Add docs for maintainers on releasing

lib/src/klio/transforms/io.py, lib/tests/unit/transforms/test_io.py
Because beam 2.25 changed `BigQuerySource` to a function, we'll instead create `KlioReadFromBigQuery` as a custom `PTransform` that just combines beam's `ReadFromBigQuery` with a separate mapper that does the BQ row to `KlioMessage` conversion.
Beam has made quite a few breaking changes over the last few versions and this is the only approach that is compatible with both older (2.22) and newer (2.25) versions.
Tested this so far on both direct-runner and dataflow with beam 2.24 and 2.25.
This PR does _not_ remove the `<2.25` restriction on beam, but only because it leads to other google lib version conflicts.  Luckily #111 will address that (in my tests I merged that branch in to test on 2.25)
=> [lib] rewrite KlioReadFromBigQuery as reader + map transform

lib/src/klio/transforms/decorators.py
=> [lib] Add handling of yielded exceptions from functions decorated with @handle_klio

docs/src/reference/lib/changelog.rst, lib/setup.cfg, lib/src/klio/__init__.py
=> [lib] Bump version from lib-0.2.0.post1 -> lib-0.2.1

cli/setup.cfg, cli/src/klio_cli/__init__.py, core/setup.cfg, core/src/klio_core/__init__.py, devtools/setup.cfg, devtools/src/klio_devtools/__init__.py, docs/src/reference/cli/changelog.rst, docs/src/reference/core/changelog.rst, docs/src/reference/devtools/changelog.rst, docs/src/reference/executor/changelog.rst, docs/src/reference/lib/changelog.rst, exec/setup.cfg, exec/src/klio_exec/__init__.py, lib/setup.cfg, lib/setup.py, lib/src/klio/__init__.py
=> Bumpversions cli exec devtools core lib

docs/src/keps/index.rst, docs/src/keps/kep-002.rst
Add the Accepted KEP 2 proposal. Its status will get updated to "Final" when the implementation is done.
@spotify/klio-devs please let me know if I've captured the relevant/important points in the Discussion section. Also, I think it might be a good idea to leave the final naming (e.g. arg names, class names, etc) and technical specifics to the eventual review of PR that implements this.
=> [kep] Add accepted KEP 2 on thread management

lib/src/klio/transforms/io.py, lib/tests/unit/transforms/test_io.py
Add ``KlioWriteToAvro`` to enable users to write an avro file.
To allow this to be used as an event output write or as a generic write, we treat ``element`` as a reserved field. If the field ``element`` is present in the record to be written then that field will be set to the .
. If the field ``element`` is not present then the entire record will be cast to bytes and stuffed into the KlioMessage.data.element field.
I have included unit tests.
One unit test to test the logic of writing to an avro file and another to test the seamless, unchaged data between reading from an avro file then writing then re-reading. (Open to getting rid of this latter test if we think it may be an overkill)
=> [lib] Add KlioWriteToAvro

docs/src/reference/lib/changelog.rst, exec/README.rst, lib/setup.cfg, lib/src/klio/__init__.py
Bumping versions klio-lib 0.2.1.post2 -> 0.2.2
No logic changes
=> [lib] Bumpversion klio-lib 0.2.1.post2 -> 0.2.2

.github/workflows/docs.yml, cli/setup.cfg, cli/src/klio_cli/__init__.py, docs/klio-requirements.txt, docs/src/reference/cli/changelog.rst
This release includes fixes for "Invalid constructor" errors in the `verify`, `delete`, and `message` commands (#136).
=> [cli] Release 1.0.3

cli/tests/test_cli.py, core/src/klio_core/_testing.py
The `MockKlioConfig` testing class that bundles together a bunch of mocks doesn't currently allow for testing with a custom `job_dir`.
In the process it also became apparent that many of our tests are not testing custom `job_dir` so I'll also be adding it to a couple tests.
I think, though, there is actually larger work that could be done to break up some of our cli tests.  Now that `@with_klio_config` encapsulates a lot of these CLI options, we don't need to be testing them in every cli test.
=> [core,cli] support job_dir in testing, test cleanup

docs/src/keps/index.rst, docs/src/keps/kep-002.rst, docs/src/reference/lib/api/transforms/decorators.rst, docs/src/reference/lib/api/utils/index.rst, docs/src/reference/lib/changelog.rst, docs/src/reference/lib/index.rst, docs/src/userguide/pipeline/utilities.rst, integration/audio-spectrograms/run.py, integration/batch-modular-default/run.py, integration/multi-event-input-batch/run.py, integration/read-file/run.py, lib/src/klio/transforms/decorators.py, lib/src/klio/transforms/helpers.py, lib/src/klio/utils/__init__.py, lib/src/klio/utils/_thread_limiter.py, lib/tests/unit/transforms/test_decorators.py, lib/tests/unit/transforms/test_helpers.py, lib/tests/unit/utils/__init__.py, lib/tests/unit/utils/test_thread_limiter.py
This PR implements [KEP 2](https://docs.klio.io/en/latest/keps/kep-002.html) and is based off of #122. 
I've included unit tests and have successfully run jobs with the added code.
=> [lib, docs] Add thread management to Klio-ified transforms

exec/tox.ini, integration/audio-spectrograms/Dockerfile, integration/audio-spectrograms/job-requirements.in, integration/audio-spectrograms/job-requirements.txt, integration/batch-modular-default/Dockerfile, integration/batch-modular-default/job-requirements.in, integration/batch-modular-default/job-requirements.txt, integration/multi-event-input-batch/Dockerfile, integration/multi-event-input-batch/job-requirements.in, integration/multi-event-input-batch/job-requirements.txt, integration/read-bq-write-bq/Dockerfile, integration/read-bq-write-bq/job-requirements.in, integration/read-bq-write-bq/job-requirements.txt, integration/read-bq-write-bq/klio-job.yaml, integration/read-file-write-file/Dockerfile, integration/read-file-write-file/job-requirements.in, integration/read-file-write-file/job-requirements.txt, integration/read-file/Dockerfile, integration/read-file/job-requirements.in, integration/read-file/job-requirements.txt, lib/tox.ini
...as well as update the integration tests to use the latest Beam SDK.
=> [lib,exec,IT] Add Beam SDK versions 2.26 and 2.27 to testing matrices

docs/src/reference/executor/changelog.rst, docs/src/reference/lib/changelog.rst, exec/setup.cfg, exec/src/klio_exec/__init__.py, lib/setup.cfg, lib/src/klio/__init__.py
=> release exec-0.2.2, lib-0.2.4

core/src/klio_core/config/core.py, core/tests/config/test_config.py
Because `KlioPipelineConfig` reformats `worker_disk_type`, and because `klioexec` is potentially reading config files written by `klio-cli`, we need config to be able to parse both the unformatted and formatted versions.
=> [core] allow config to accept formatted worker_disk_type

docs/src/userguide/config/index.rst
As the PR title says, I've added some prose documentation that is meant to complement the CLI's reference/API docs for templating and overriding values in a job's configuration.
=> [docs] Add prose docs on templating and overriding config

docs/src/conf.py, docs/src/userguide/config/event_config.rst, docs/src/userguide/io/index.rst
Just as the title says:
* Add event I/O configuration documentation for reading from/writing to files
* Add event output configuration documentation for writing to BQ (reading already existed)
=> [docs] Add event config docs for reading/writing files and writing to BQ

docs/src/userguide/anatomy/job.rst
Add a batch section to the [jobs overview](https://docs.klio.io/en/latest/userguide/anatomy/job.html) in the User Guide.
=> [docs] Update Userguide/Anatomy/Overview to include batch

docs/src/userguide/config/data_config.rst
Smallest doc change ever. But as we have seen, it does make a difference.
Add a `.` in front of `ogg` in the code config example of `file_suffix`
None, just a docs change
=> [docs] Add . in file_suffix example using .ogg

core/src/klio_core/config/_io.py, docs/src/reference/core/changelog.rst, docs/src/reference/lib/api/transforms/index.rst, docs/src/reference/lib/api/transforms/io.rst, docs/src/userguide/config/event_config.rst, docs/src/userguide/io/index.rst, exec/src/klio_exec/commands/run.py, lib/src/klio/transforms/__init__.py, lib/src/klio/transforms/io.py
Added KlioWriteToAvro as importable event type
Added KlioWriteToAvro exposed in docs
Added batch event IO
Ran KlioWriteAvro as default event output write by using klio devtools on a job with avro + location configured as event output.
=> [exec][lib][docs] Add KlioWriteToAvro as event type, Add docs for batch event IO

docs/src/faqs/index.rst, docs/src/faqs/streaming_to_batch_conversion.rst, docs/src/quickstart/hello_klio_batch.rst, docs/src/quickstart/hello_klio_streaming.rst, docs/src/quickstart/index.rst, docs/src/userguide/config/pipeline_options.rst
- Add quickstart example for Klio Batch
- Add guide on how to convert a streaming job to a Klio batch job
Will build docs locally and make sure it looks fine.
=> [docs] Streaming to batch conversion guide, Batch HelloKlio quickstart

docs/src/userguide/anatomy/files.rst, docs/src/userguide/anatomy/graph.rst
Updates `Files` and `Graph` sections to include batch.
- [x ] Format the pull request title like `[cli] Fixes bugs in 'klio job fake-cmd'`.
=> [docs] Update graph and file sections in User Guide / Anatomy to include batch

docs/src/userguide/config/job_config.rst, docs/src/userguide/pipeline/index.rst, docs/src/userguide/pipeline/io.rst, docs/src/userguide/pipeline/multiple_inputs.rst
I noticed we didn't have any prose docs on multiple event inputs so I quickly drafted some up 😄
=> [docs] Add prose docs on multiple event inputs

core/setup.cfg, core/src/klio_core/__init__.py, docs/src/reference/core/changelog.rst
=> [core] Release 0.2.2

README.rst
=> [docs] fix broken link

docs/src/conf.py
docs builds are failing due to this apparently broken link, so add it to the ignore list for now.
=> [docs] adding ignore to broken matplotlib link

docs/src/index.rst, docs/src/reference/cli/changelog.rst, docs/src/reference/core/changelog.rst, docs/src/reference/executor/changelog.rst, docs/src/reference/lib/changelog.rst, docs/src/release_notes/21.2.0.rst, docs/src/release_notes/index.rst, docs/src/userguide/config/index.rst, docs/src/userguide/pipeline/io.rst
Add a top-level page for Klio's release notes.
**One question**: When merged, this will not be included in [docs/21.2.0](https://docs.klio.io/en/21.2.0/) build (aka [docs/stable](https://docs.klio.io/en/stable/)) because it's not included in the `21.2.0` git tag (it will be in [docs/develop](https://docs.klio.io/en/latest/) though). Should we retag to it is included? If we do retag it, it will include the commit 1bd85821 (@fallonchen 's #180 ) and merge commits 171250a3 and 5824e192. Perhaps we skip for now, but include in the release process to have these release notes in alongside everything else?
Also, I hope to someday make this automated, so we don't have to add the `start-*`, `end-*`, and ref tags for every release.
Just for reference, I took a look at how numpy does [release …
=> [docs] Add new release notes page

exec/setup.py, exec/tests/unit/commands/runners/test_gke_direct.py
=> [exec] Add basic GkeDirectRunner tests

exec/src/klio_exec/runners/gke_direct.py, exec/src/klio_exec/runners/pubsub_message_manager.py
=> [exec] Add docstrings

cli/setup.cfg, cli/src/klio_cli/__init__.py, core/setup.cfg, core/src/klio_core/__init__.py, exec/setup.cfg, exec/src/klio_exec/__init__.py, lib/setup.cfg, lib/src/klio/__init__.py
=> 21.7.0.dev1 version bumps

docs/src/faqs/run_on_kubernetes.rst, docs/src/reference/cli/changelog.rst, docs/src/reference/core/changelog.rst, docs/src/reference/executor/changelog.rst, docs/src/reference/lib/changelog.rst, docs/src/release_notes/21.8.0.rst, docs/src/release_notes/index.rst
We havent made a release in a while and the features keep piling up.
This PR is to combine all the features we havent released, update the changelogs and update the release notes page to get on top of all the changes.
I mainly went through the and looked at the PRs that have been merged in since our last releases and made sure they were accounted for in the changelog
Will look at docs builds
=> [docs] Update changelogs to combine all unreleased features; add a release notes page for 21.8.0

cli/src/klio_cli/commands/job/gke.py, cli/tests/commands/job/test_gke.py
Make it easier for users to access the GKE UI.
=> [cli] Output GKE UI link whenever deployment updates

cli/setup.cfg, cli/setup.py, cli/src/klio_cli/__init__.py, core/setup.cfg, core/src/klio_core/__init__.py, docs/src/reference/lib/changelog.rst, exec/setup.cfg, exec/setup.py, exec/src/klio_exec/__init__.py, lib/setup.cfg, lib/setup.py, lib/src/klio/__init__.py
Also noticed I forgot to update the changelog on an earlier PR, so including that as well.
=> 21.9.0.dev1 version bumps

exec/src/klio_exec/__init__.py
Otherwise, 'python setup.py build' fails with multi-line descriptions.
Open to better descriptions! A bit hard as it needs to fit on one line.
=> [exec] Update pkg desc to be single-lined

docs/src/release_notes/21.12.0.rst, docs/src/release_notes/index.rst
Add a releasenote for 21.12.0
Served docs locally to test formatting
=> [docs] Add releasenote for 21.12.0

docs/src/reference/devtools/changelog.rst, docs/src/release_notes/22.3.0.rst, docs/src/release_notes/index.rst
This should also get merged into master
Add changelog for 22.3.0 release
=> [docs] Add releasenote for 22.3.0
