spotify/klio

- devtools/src/klio_devtools/cli.py
- devtools/src/klio_devtools/commands/develop.py
few small updates to devtools I found helpful:
1.  `pip` now uses the `2020-resolver` feature.  
2.  added a `--exclude` option to exclude installing a package.  Kinda only makes sense for `klio-audio` right now, but I found it useful since that one take the longest to install and usually isn't needed
3.  minor refactoring
> [devtools] use 2020-resolver, new package exclude option

- exec/setup.py
- exec/src/klio_exec/commands/audit_steps/multithreaded_tf.py
- exec/src/klio_exec/commands/audit_steps/numpy_broken_blas.py
- exec/tests/unit/commands/audit_steps/conftest.py
- exec/tests/unit/commands/audit_steps/test_multithreaded_tf.py
- exec/tests/unit/commands/audit_steps/test_numpy_broken_blas.py
- exec/tests/unit/commands/audit_steps/test_tempfile_usage.py
Adding two audit steps: one that warns when a job w/ tensorflow is running w/ multiple threads on dataflow, and errors when an older, broken version of numpy is installed.
> [exec] Add multithread tf & numpy version audit steps

- cli/setup.py
Fixing a dependency version conflict:
```
google-cloud-monitoring 2.0.0 requires google-api-core[grpc]<2.0.0dev,>=1.22.2, but you'll have google-api-core 1.20.1 which is incompatible.
```
> [cli] set google-cloud-monitoring < 2.0.0

- docs/src/_static/css/custom.css
Change Github icon css to light theme so it stands out on dark topnav.
> [docs] Light Github Icon css

- microsite/css/main.css
On safari (desktop and mobile), the icons looked weird:
There may be a smarter way but I'm not a front end person and this is a quick fix ¯\\_(ツ)_/¯
> [site] Fix icon sizes for non-chrome browsers

- lib/setup.py
2.25.0 has transitive dependencies that cause conflicts:
```
google-cloud-build 2.0.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.22.0, but you have google-api-core 1.20.1.
google-cloud-bigquery 1.28.0 has requirement google-api-core<2.0dev,>=1.21.0, but you have google-api-core 1.20.1.
```
Also, `2.25.0` has changed `BigQuerySource` from a class to a function, and since we have classes that inherit from it, Klio is currently incompatible with it.
> [lib] limit apache-beam version <2.25.0

- cli/setup.cfg
- cli/src/klio_cli/__init__.py
Releasing cli-1.0.1, which includes:
**Fixes**
* [PR 100](https://github.com/spotify/klio/pull/100): set google-cloud-monitoring < 2.0.0. This impacts users who have encountered the infinite dependency resolution issue in versions of pip using the new 2020 resolver [issue](https://github.com/pypa/pip/issues/9011).
> [cli] Bump version: 1.0.0 → 1.0.1

- cli/src/klio_cli/commands/job/create.py
- cli/src/klio_cli/commands/job/utils/templates/dockerfile.tpl
- cli/tests/commands/job/test_create.py
- cli/tests/commands/job/utils/fixtures/expected/fnapi/Dockerfile
- cli/tests/commands/job/utils/fixtures/expected/no_fnapi/Dockerfile
Base the job generated from `klio job create` on the apache beam images, rather than the Dataflow ones.
Since the shortened form of the Python version was kept around just to build the name of the Dataflow Docker image, remove its use.
> [cli] Use apache beam images in job create templates

- cli/src/klio_cli/commands/job/verify.py
- cli/tests/commands/job/test_verify.py
Currently the `klio job verify` command has functionality for verifying that the job's inputs and outputs are correctly configured. This is all currently hard-coded to assume that event-I/O is pubsub and data I/O is GCS.
Going forward these checks need to be more modular so that the checks performed match the actual type of I/O.
For now we should not error out on other types of solutions.
> [cli] Remove checks for topic/subscription in event input/output when event types are not pubsub

- .github/workflows/dependencies.yml
- cli/setup.py
- core/setup.py
- exec/tox.ini
- lib/setup.py
- lib/tests/unit/transforms/test_core.py
- lib/tox.ini
* Removing most of the versions restriction on google lib dependencies.
* including testing with beam 2.25 (left 2.22 in for now but we can probably stop testing on it soon)
* removing use of `2020-resolver` in dependency check workflow because of pip issues
> [cli, core, exec, lib] unpin google lib versions, support beam 2.25

- cli/src/klio_cli/cli.py
- cli/src/klio_cli/commands/base.py
- cli/src/klio_cli/commands/job/run.py
- cli/tests/commands/job/test_run.py
- cli/tests/commands/test_base.py
- cli/tests/test_cli.py
- core/src/klio_core/_testing.py
- core/src/klio_core/utils.py
- core/tests/test_utils.py
- devtools/src/klio_devtools/commands/develop.py
- exec/src/klio_exec/cli.py
- exec/tests/unit/commands/test_run.py
- exec/tests/unit/test_cli.py
- lib/src/klio/transforms/core.py
- lib/tests/unit/conftest.py
- lib/tests/unit/transforms/test_core.py
Two main important changes in this PR:
When CLI `run` invokes exec `run`, it now generates a "materialized" config file on the fly and hands it off to exec (purposely using "materialized" instead of "effective" to eliminate any possible confusion with the existing effective config).  This file includes any overrides and template parameters applied, so exec doesn't have to worry about any of that and just reads the generated file as-is.  
This basically solves the problem of how to propagate config overrides from CLI to exec.
Note: since we have since decided to add all config parsing support to exec to support Luigi (which will bypass CLI and call exec directly), an alternative approach could have been to simply pass-on all overrides as command-line parameters when CLI invokes exec. …
> [cli, exec, lib] Remove effective-klio-job.yaml

- docs/src/userguide/config/event_config.rst
- docs/src/userguide/io/index.rst
- lib/src/klio/transforms/io.py
Document using BigQuery as an event input source, making sure to cover the fact that if only one `column` is specified,   the input value will be returned as a plain bytestring, while specifying either no or multiple column fields will result in a JSON serialized bytestring containing the contents of the row. 
Update: Also includes a short indentation fix for the `KlioReadFromBigQuery` docstring - without this fix, we encounter a `sphinx` build error: 
```docstring of klio.transforms.io.KlioReadFromBigQuery:5:Definition list ends without a blank line; unexpected unindent.```
- [ x] Document any …
> [docs] Add BigQuery event inputs to user guide

- docs/src/reference/lib/changelog.rst
- lib/setup.cfg
- lib/setup.py
- lib/src/klio/__init__.py
Solves this issue here:
```
File "/usr/local/lib/python3.6/site-packages/apache_beam/transforms/userstate.py", line 281, in validate_stateful_dofn
all_state_specs, all_timer_specs = get_dofn_specs(dofn)
File "/usr/local/lib/python3.6/site-packages/apache_beam/transforms/userstate.py", line 250, in get_dofn_specs
if not isinstance(getattr(dofn, method_name, None), types.MethodType):
File "/usr/local/lib/python3.6/site-packages/klio/transforms/_helpers.py", line 169, in _data_config
if len(self._klio.config.job_config.data.inputs) > 1:
File "/usr/local/lib/python3.6/site-packages/klio/transforms/core.py", line 114, in config
return RunConfig.get()
File "/usr/local/lib/python3.6/site-packages/klio/transforms/core.py", line 34, in get
"Attempt to access RunConfig before it was set. This …
```
> Bumpversion klio-0.2.1 -> klio-0.2.1.post

- exec/src/klio_exec/commands/run.py
- exec/tests/unit/commands/test_run.py
Since the FnAPI is not yet stable for batch jobs, warn if it is being used.
If it is not used and neither `requirements.txt` nor `setup.py` are being used to package dependencies, exit with an error.
- [x ] Changes are covered by unit tests (no major decrease in code coverage %) and/or integration tests.
> [exec] Validate batch job packaging

- docs/src/reference/lib/changelog.rst
- lib/src/klio/transforms/_helpers.py
- lib/src/klio/transforms/helpers.py
We allow users to not have to define inputs and/or outputs under `job_config.data` in their klio-job.yaml. But these helper filter transforms (`KlioFilterForce` and `KlioFilterPing`) implicitly expected data config to be there, when that shouldn’t be the case. This is a small (maybe not the most ideal) work around for that (tbh not sure what the most ideal way would be to approach this, but this was quick ¯\\_(ツ)_/¯ ).
I successfully ran jobs that have otherwise failed with issue.
> [lib] Support empty data config for helper filter transforms

- docs/src/reference/cli/index.rst
- docs/src/reference/executor/api.rst
- docs/src/reference/executor/index.rst
Adds reference documentation for the klioexec CLI.
> [docs] Add reference docs for klioexec 

- exec/src/klio_exec/commands/run.py
- exec/tests/unit/commands/test_run.py
Since Klio jobs are inherently multi-module, a `requirements.txt` file is not sufficient to package a klio job. This PR removes the misleading check for the existence of the `requirements.txt` file.
> [exec] Remove misleading references to requirements.txt for batch packaging

- cli/src/klio_cli/commands/job/test.py
- cli/tests/commands/job/test_test.py
`klio-cli` passes the `--config-file` flag to `klioexec test`, even though `klioexec test` does not accept `config-file` as an argument. This causes `klioexec` to complain that it doesn't recognize the argument, as shown below:
```
klio job test
INFO:root:Found worker image: gcr.io/spotify-audio-intelligence-2/language-classification-klio-job-worker:f9e0c53e
ERROR: usage: klioexec [options] [file_or_dir] [file_or_dir] [...]
klioexec: error: unrecognized arguments: --config-file
inifile: None
rootdir: /usr/src
```
This PR solves this by setting the `requires_config_file` in `TestPipeline` to `False` , which makes it so that `klio-cli` does not pass the `--config-file` flag.
> [cli] Set requires_config_file to False in TestPipeline

- docs/src/reference/lib/changelog.rst
- lib/setup.cfg
- lib/src/klio/__init__.py
- lib/src/klio/message/serializer.py
- lib/src/klio/transforms/helpers.py
- lib/tests/unit/message/test_serializer.py
When working on my Klio pet, I noticed two things wrong with Klio serialization:
1. When working with non-Klio messages, Klio will load the whole non-Klio message into `kmsg.data.element` (as expected). But it did not set the message version or the recipients, both of which are expected in other parts of the code. The first commit addresses that.
2. Some of the helper transforms take in a raw pubsub message and need to serialize it into a Klio message. They were not providing all the required function arguments when serializing to Klio message, and the second commit addresses that.
* Updated unit tests
* Successfully ran my Klio pet job with these changes
> [lib] Bugfix: klio serialization in helpers & for non-klio messages.

- lib/setup.py
I noticed when releasing `klio==0.2.3` to PyPI, that it was pulling in `klio-exec`'s long description information. When releasing `klio==0.2.3`, I made this change locally so it will look correct on PyPI. I checked the other packages and all are fine - I'm guessing it was copy-pasta.
> [lib] Fix which changelog to read from for long desc

- cli/setup.cfg
- cli/src/klio_cli/__init__.py
- docs/src/reference/cli/changelog.rst
This release fixes a bug in the `klio job test` command that causes the user to receive the error `klioexec: error: unrecognized arguments: --config-file` (#140)
> [cli] Release 1.0.4

- cli/src/klio_cli/cli.py
- cli/src/klio_cli/commands/base.py
- cli/tests/test_cli.py
- core/src/klio_core/_testing.py
- core/src/klio_core/config/_preprocessing.py
- core/src/klio_core/config/core.py
- core/src/klio_core/utils.py
- core/tests/config/test_config.py
- core/tests/config/test_preprocessing.py
- docs/src/reference/cli/changelog.rst
- docs/src/reference/core/changelog.rst
Looks like we weren't actually applying the transform on raw config that converted the lists of I/O to nested dicts.  Luckily this had no real effect except on correctly handling overrides.
> [core] fix preprocessing of config io fields

- core/setup.py
- core/src/klio_core/config/core.py
- core/tests/config/test_config.py
This fixes a bug where calling `klio_config.as_dict()` in a transform would not include user-defined config keys only when executed in dataflow.
Basically `USER_ATTRIBS` was defined as a class-level attribute, which means it would not get pickled with other class attributes when sent to dataflow.  This explains that while the keys didn't appear in the generated dict, they did exist on dataflow through direct access.
> [core] fixing config as_dict not including custom keys on dataflow

- integration/batch-modular-default/tests/test_transforms.py
- integration/read-bq-write-bq/tests/test_transforms.py
- integration/read-file-write-file/tests/test_transforms.py
- integration/read-file/tests/test_transforms.py
- integration/scripts/tox_commands.sh
Before, integration tests would succeed even if `klio job test` or `klio job run` failed. The success of the testing would just depend on how the very last command in `tox_commands.sh` did.
I introduced a few minor failures when merging in #135 (expected logs didn't match actual logs), so I fixed those as well.
> [integration] Fail if `klio job test` or `klio job run` fails during integration tests

- exec/src/klio_exec/cli.py
- exec/tests/unit/test_cli.py
- lib/src/klio/transforms/core.py
- lib/tests/unit/transforms/test_core.py
This is a partial revert for f58caf7224807793082b922d368acff03ba76978.
In some cases for unknown reasons, `RunConfig.get()` will begin raising an exception that the config is no longer set.  This should not be happening, and in some instances the problem doesn't show up until a streaming job has been running for hours, but there is likely some underlying issue in Beam/Dataflow that is leading the main session variable to be deleted.
This PR is not intended to be a complete fix, but rather a mitigation that reverts back to `klioexec` getting its config via the `effective-klio-job.yaml` that should be included with the packaged code.
I've left the `klio-cli` changes untouched, meaning it will continue to write a temp file and bind it for use by `klioexec`.  `klioexec` will also still set …
> [exec,lib] partial revert of using main_session for KlioConfig

- cli/src/klio_cli/commands/job/create.py
- cli/src/klio_cli/commands/job/utils/gcp_setup.py
- cli/tests/commands/job/test_create.py
- cli/tests/commands/job/utils/test_gcp_setup.py
- docs/src/reference/cli/changelog.rst
Add more general language to `klio job create` prompts
Fix errors caused by wrong function call when batch job made from cli
Fix `klio job create` so klio will not try to make topics and subscriptions for batch jobs
Unit test coverage
Used command to create a batch job and a streaming job
> [cli] Fix klio job create for batch job creation

- docs/src/faqs/index.rst
- docs/src/faqs/migrate_from_fnapi.rst
- docs/src/faqs/migrate_from_setup.rst
- docs/src/faqs/setup_packaging.rst
- docs/src/userguide/anatomy/files.rst
Since FnAPI is still experimental (and will be for quite some time), make documentation assume that the default is to use `setup.py` for packaging, rather than FnAPI.
- [x ] Format the pull request title like `[cli] Fixes bugs in 'klio job fake-cmd'`.
> [docs] De-emphasize references to FnAPI

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/integration.yml
- CONTRIBUTING.rst
- RELEASING.rst
- docs/src/conf.py
This PR mainly adds guidance on when to add changelog entries and how to prepare the changelog for releasing.
There are two additional small improvements:
* Updating docs config to remove ignored items that now actually work (I quickly checked all ignored items to see if they fail `make stricthtml` or `make linkcheck`)
* Update CI workflows to either trigger when `**.rst` files change (like re-build docs), or to not trigger workflows (no need to trigger integration tests when `RELEASING.rst` changes)
> [docs] Add changelog guidance

- core/src/klio_core/config/_io.py
Description : 
When trying to output my pipeline to BigQuery, my klio job fails because it does not parse the BQ schema in the YAML file into a valid dictionary : 
```
(klio) DMFR0900:data-thumbnails-classification p.genissel$ klio job run --direct-runner --template execution_date="2021-01-10 00:00:00"
INFO:root:Found worker image: gcr.io/dailymotion-rawlogs/data-thumbnails-classification-worker:4c5784c5-dirty
Traceback (most recent call last):
File "/usr/local/bin/klioexec", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click/core.py", …
```
> [core] Added JSON converter in KlioBigQueryEventOutput

- docs/src/_static/css/custom.css
- docs/src/reference/lib/api/metrics/index.rst
- docs/src/reference/lib/api/metrics/native.rst
- docs/src/reference/lib/changelog.rst
- docs/src/userguide/pipeline/metrics.rst
- lib/src/klio/metrics/dispatcher.py
- lib/src/klio/metrics/native.py
- lib/src/klio/metrics/stackdriver.py
- lib/src/klio/transforms/core.py
- lib/tests/unit/metrics/test_native.py
- lib/tests/unit/metrics/test_stackdriver.py
- lib/tests/unit/transforms/test_core.py
- lib/tests/unit/transforms/test_decorators.py
For some reason, the ability to create custom log metrics in Stackdriver no longer works. Rather than spending time trying to understand why and how to fix it, now that Dataflow supports collecting metrics from Beam's native metrics implementation (so beam metrics are automatically emitted to and reported by Dataflow's monitoring when running on Dataflow), I've decided to leverage that instead and mark the Stackdriver log-based metrics as deprecated.
I went on the assumption that we could make a March release (`21.3.0`) but it's just a placeholder - doesn't have to be for our March release.
The next steps after this:
* Add metrics that are reported by default from our library of transforms (e.g. message consumed, message processed, message errored, message retried, message processed …
> [lib,docs] Deprecate Stackdriver log-based metrics for new native Beam metrics

- cli/src/klio_cli/commands/job/test.py
- cli/tests/commands/job/test_test.py
`klio job test` currently takes in the `--config-file` option but does nothing with it, since the `requires_config_file` flag is set to `False`. 
The config file option was also ignored in `klio-exec`, but that was fixed via [PR 177](https://github.com/spotify/klio/pull/177).
This PR sets enables the use of the `--config-file` option by doing 2 things:
1. Setting `TestPipeline().requires_config_file` to `True`. 
2. This PR also adjusts the way `TestPipeline` handles command generation so that the `--config-file` option is appended after the `test` command, but before pytest arguments are added. 
Before this change, the generated command would be: 
```klio job test -- py_arg1 pyarg2 ... pyargN --config-file config.yaml```
This causes the `--config-file` option to be ignored. 
After this …
> [cli] Enable job test command to use the --config-file option

- cli/src/klio_cli/commands/job/profile.py
- cli/tests/commands/job/test_profile.py
Since `ProfilePipeline` overrides `run` and was missing the call to `_write_effective_config()`, `klio job profile` commands were erroring out if `klio-job-run-effective.yaml` was missing.  This PR just adds the call to fix the issue.
Note: I took a quick look at perhaps changing where this call is managed, so sub-classes overriding `run` wouldn't have to worry about it, but since `profile` is the only such command I decided not to over complicate things for now.
> [cli] effective config is properly written for profile commands

- docs/src/conf.py
- docs/src/reference/lib/api/transforms/helpers.rst
- docs/src/reference/lib/api/transforms/index.rst
- exec/setup.py
- integration/audio-spectrograms/expected_job_output.txt
- integration/audio-spectrograms/run.py
- lib/src/klio/transforms/_helpers.py
- lib/src/klio/transforms/_retry.py
- lib/src/klio/transforms/_timeout.py
- lib/src/klio/transforms/decorators.py
- lib/src/klio/transforms/helpers.py
- lib/src/klio/transforms/io.py
- lib/tests/unit/conftest.py
- lib/tests/unit/transforms/test_core.py
- lib/tests/unit/transforms/test_decorators.py
- lib/tests/unit/transforms/test_helpers.py
- lib/tests/unit/transforms/test_io.py
This is part 1 of adding default metrics. Part 2 seems to be a bit more hairy (more info below).
This PR adds code to emit metrics for the following transform classes, with the name of the metric in parens (the name shows up in the dataflow UI):
* io transforms:
* `KlioReadFromText`  (`kmsg-read`)
* `KlioReadFromBigQuery` (`kmsg-read`)
* `KlioReadFromAvro` (`kmsg-read`)
* `KlioWriteToText` (`kmsg-write`)
* `KlioWriteToBigQuery` (`kmsg-write`)
* `KlioWriteToAvro` (`kmsg-write`)
* helper transforms:
* `KlioGcsCheckInputExists` (`kmsg-data-found-input`, `kmsg-data-not-found-input`)
* `KlioGcsCheckOutputExists` (`kmsg-data-found-output`, `kmsg-data-not-found-output`)
* `KlioFilterPing` (`kmsg-process-ping`, `kmsg-skip-ping`)
* `KlioFilterForce` (`kmsg-process-force`, `kmsg-skip-force`)
* …
> [lib, docs] Add default metrics for batch IO transforms, and retry & timeout decorator

- docs/src/_templates/layout.html
- docs/src/reference/lib/api/metrics/index.rst
- docs/src/reference/lib/api/metrics/shumway.rst
- lib/setup.py
- lib/src/klio/metrics/shumway.py
- lib/src/klio/transforms/core.py
- lib/tests/unit/metrics/test_shumway.py
Adds a user-facing metrics interface for [shumway](https://github.com/spotify/shumway) for when log-based metrics is not feasible. I skipped adding a note in `klio`'s changelog since I'm not sure what version this will be released in (alpha, beta, or release candidate).
* "I have included unit tests" 
* "I successfully ran my jobs with this code"
> [lib] Add metrics interface for shumway

- cli/setup.py
- exec/setup.py
- lib/setup.py
Just bumping dependencies on other klio libs for easier testing.
~Keeping in line with our plans to open PR's against `develop` until we hit post-dev stage.  Will rebase `release-21.7.0.dev1` on `develop` after merging.~  
Well that didn't work.   Since the version bumps themselves are in the `release-21.7.0` branch, I need to base this against that.  I think it may also make sense to merge that branch into `develop` and just cut further `dev` releases directly from `develop` until we're ready to actually start the general release process.
> [cli,exec,lib] bump cross-package dependencies to 21.7.0.dev1

- cli/src/klio_cli/commands/message/publish.py
- docs/src/faqs/performance.rst
- docs/src/reference/cli/changelog.rst
When using `google-cloud-pubsub` `2.5.0`, `klio message publish` will say that the message is successfully published, but the message is not actually published to the topic.  This appears to have been some underlying threading change causing a race condition where `klio-cli` doesn't wait on the returned `Future` and exits before the message is actually published.
Simply blocking on the future fixes the issue.  I tested with pubsub `2.0.0`, `2.3.0` and `2.5.0`.
This is just a quick fix and there is room for further improvement.  If multiple messages are being published, this will end up blocking for each message, which is a bit inefficient since the pubsub client does have internal batching capabilities, but for small numbers of messages it shouldn't be big deal.
> [cli] klio message publish blocks on pubsub client future

- cli/setup.cfg
- cli/src/klio_cli/__init__.py
- cli/src/klio_cli/commands/message/publish.py
- core/setup.cfg
- core/src/klio_core/__init__.py
- docs/src/faqs/performance.rst
- docs/src/reference/cli/changelog.rst
- exec/setup.cfg
- exec/src/klio_exec/__init__.py
- lib/setup.cfg
- lib/src/klio/__init__.py
This includes new commits in `develop` since `dev1` (just one that fixes `klio message publish`) and version bumps all packages to `21.7.0.dev2`.
I have included a merge commit instead of manually rebasing `release-21.7.0` because doing that would change the commit sha's of the previous `dev1` version bump commits and subsequently orphan the git tags pointing to them.  If we don't think that's a big deal, rebasing may be cleaner in terms of commit history.
Either way, I haven't pushed git tags for `dev2` yet but will once this PR is merged.
> release 21.7.0.dev2

- lib/src/klio/message/pubsub_message_manager.py
- lib/tests/unit/message/test_pubsub_message_manager.py
This PR contains two fixes/commits for two separate bugs seen while running direct on GKE. For both bugs, this was on python 3.8, apache beam 2.28, and klio* 21.7.0.dev2.
The first commit fixes a bug where the pubsub manager workers get stuck in the `while` loop and can't consume new messages. The behavior we've seen when testing this is that a message would be consumed, processed, and acked, but the heartbeat still continues (as seen with the log line `"Job is still processing <ID>"` every 10 seconds) and no new messages are consumed. How it gets into this state is unknown, but reproducible. This patch is more of a work-around where the heartbeat checks to see if the message is actually still in memory and if not, to ack (just in case) and break out of the loop.
The second commit fixes a …
> [lib] Fix pubsub mgr with (1) being stuck in while loop and (2) missing msg extension deadline

- cli/src/klio_cli/commands/job/gke.py
- cli/tests/commands/job/test_gke.py
Add fetching of active cluster name for use in messaging
@fallonchen can make use of this when adding the dashboard links to output of running a job
Installed new version of klio cli and tested running and deleting klio jobs and ensuring messaging currectly reflects current context.
> [cli] Add current context and cluster name to messaging

- cli/src/klio_cli/commands/job/gke.py
- cli/tests/commands/job/test_gke.py
- docs/src/reference/cli/changelog.rst
Add a warning message for user if the configured image to be built does not match the image that will be deployed when using DirectOnGKE
Any thoughts on whether we should release everything in a 21.8.0 release or release the things we have already tested thoroughly?
- Installed cli and tested running a job with mismatched image
- Added unit test coverage to ensure warning message is seen when images are mismatched
> [cli] Add safety check for image build vs deploy name for DirectGKERunner

- cli/src/klio_cli/commands/job/gke.py
- cli/tests/commands/job/test_gke.py
- integration/audio-spectrograms/job-requirements.in
This ensures required and best-practices labels are set (which is particularly helpful for cost association), as well as any labels defined in the klio job config. This also adds a "deployed by" label and a "klio cli version" label, which can be particularly helpful during debugging (we currently have this for our Dataflow runner).
Since this code is not run inside the job's docker container, I wasn't able to get other klio package versions. While users can install mis-matching packages, hopefully with the recent change to calendar versioning + releasing-all-packages-per-release approach will minimize that. If worse comes to worst, we can add code to run something like `pip freeze | grep klio` in the job's container.
* I have included unit tests
* Instead of running a job, I dumped the …
> [cli] Add k8s labels to deployments

- integration/batch-modular-default/tests/test_transforms.py
- integration/read-bq-write-bq/tests/test_transforms.py
- integration/read-file-write-file/tests/test_transforms.py
- integration/read-file/tests/test_transforms.py
- lib/src/klio/transforms/decorators.py
- lib/tests/unit/transforms/test_decorators.py
This fixes a bug with the `ThreadLimiter`  not properly wrapping user code in `DoFn` `process` methods.
Basically the current behavior is the thread limiter will acquire and release the lock before execution enters the `process` method, resulting in effectively no actual thread limiting around user code.  This happens because:
1.  in the `handle_klio` decorator, the thread limiter is used as a context manager
2. The `process` method always returns a generator.  This is regardless of whether the user code uses `return` or `yield`.
3. The decorator ends up returning the generator, and the generator is actually not invoked until some future point in execution, outside the context of the thread-limiter.  So the thread limiter correctly acquires the lock, but the lock is only held when …
> [lib] fix bug in handle_klio decorator with thread-limiting

- cli/setup.cfg
- cli/src/klio_cli/commands/job/gke.py
- cli/tests/commands/job/kubernetes/test_deployment.yaml
- cli/tests/commands/job/kubernetes/test_hpa.yaml
- cli/tests/commands/job/test_gke.py
- docs/src/reference/cli/changelog.rst
klio-cli will now look in the kubernetes directory and respect all yaml files.
Workflow:
`klio job run`: Iterate through each *.yaml, if the resource exists it will warn a user that it already exists and they should use the `--update` flag; If the resource does not exist it will create the resource.
`klio job delete`: Iterate through each *.yaml, if the resource exists, it will be deleted
`klio job stop`: Find the first  *.yaml that contains kind=Deployment. This config will be used to scale the deployment to 0 replicas.
Adjusted unit tests as well as tested manually
> [cli] Respect all k8s yaml when deploying to DirectOnGKE

- docs/src/reference/lib/changelog.rst
- lib/src/klio/transforms/core.py
- lib/tests/unit/message/test_pubsub_message_manager.py
- lib/tests/unit/transforms/test_core.py
- lib/tests/unit/transforms/test_decorators.py
- lib/tests/unit/transforms/test_helpers.py
- lib/tests/unit/transforms/test_io.py
When doing some benchmarking on streaming Dataflow, it was observed that if a job was started with large backlog of messages in Pubsub, the job would take a while to start processing messages and seem to have some throughput problems.
It was determined that the underlying cause was twofold.
1.  Dataflow will pull as many messages from pubsub at once, and Beam will attempt to create one thread per message with no upper bound.  Thus a large backlog can result in thousands of threads created simultaneously per worker machine.
2. Klio stores its cached config in a thread-local variable, which means each spawned thread must read the file from disk at least once.  Apparently when many threads are started at once, this causes some major I/O contention, which was the source of the lockup and low …
> [lib] replace config thread-local with global and thread lock

- docs/requirements.txt
- docs/src/faqs/streaming_to_batch_conversion.rst
Type for GCS files should be `file`, not `gcs`.
> [docs] Small fix to Streaming to Batch conversion FAQ

- cli/setup.cfg
- cli/src/klio_cli/__init__.py
- cli/src/klio_cli/utils/cli_utils.py
- core/setup.cfg
- core/src/klio_core/__init__.py
- docs/src/reference/cli/changelog.rst
- docs/src/reference/core/changelog.rst
- docs/src/reference/executor/changelog.rst
- docs/src/reference/lib/changelog.rst
- exec/setup.cfg
- exec/src/klio_exec/__init__.py
- lib/setup.cfg
- lib/src/klio/__init__.py
These changes include everything that was on branch `release-21.10.0`
Minimal diff comparing `21.12.0rc1` releases to up to date `21.10.0` can be seen here:
https://github.com/spotify/klio/compare/release-21.10.0...shireenk/release-21.12.0rc1?expand=1
These tags were created off of the latest commit on `shireenk/release-21.12.0rc1`
```
To github.com:spotify/klio.git
* [new tag]         cli-21.12.0rc1 -> cli-21.12.0rc1
* [new tag]         core-21.12.0rc1 -> core-21.12.0rc1
* [new tag]         exec-21.12.0rc1 -> exec-21.12.0rc1
* [new tag]         lib-21.12.0rc1 -> lib-21.12.0rc1
```
> Release 21.12.0rc1 including all changes that were on 21.10.0 dev releases

- exec/tox.ini
- lib/tox.ini
Updating Beam test matrix to include latest version of beam `2.34.0`
This PR updates a test and does not include any package-breaking changes.
Ran tox commands locally with updated `beam34` to ensure tests still pass
> [exec][lib] Update test matrices to latest version of beam (2.34.0)

- .github/workflows/build_upload_prod.yml
- .github/workflows/build_upload_test.yml
Not sure if the secrets handling works for this, though :grimacing:. I did refer to [these docs](https://github.community/t/secure-github-action-inputs/122310) that are 1.5 years old, which 🤞🏻 hopefully still works.
> [CI] Add manual trigger to build+upload workflow

- exec/setup.py
- exec/src/klio_exec/commands/run.py
We should allow users to not need to define data inputs in `klio-job.yaml`. This bug was preventing that, where a `PCollection` would be set to `None` to start with, and not updated with any pass through input pcollections since there could be no inputs to begin with. (I hope that makes sense, it's quite early in the day for me)
> [exec] Fix if passthru pcoll is None
